name: Deploy to GitHub Codespaces

on:
  push:
    branches: [ "feature/dashboard", "main" ]
    paths:
      - 'dashboard/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy-codespaces:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dashboard dependencies
      run: |
        cd dashboard
        npm install
        
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Build dashboard
      run: |
        cd dashboard
        npm run build
        
    - name: Create deployment summary
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Dashboard: Built successfully ✅" >> $GITHUB_STEP_SUMMARY
        echo "- Backend: Dependencies installed ✅" >> $GITHUB_STEP_SUMMARY
        echo "- MongoDB: Configured for Atlas ✅" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Open GitHub Codespaces" >> $GITHUB_STEP_SUMMARY
        echo "2. Run: \`cd dashboard && npm run dev\`" >> $GITHUB_STEP_SUMMARY
        echo "3. Run: \`cd backend && python -m uvicorn main:app --host 0.0.0.0 --port 8000\`" >> $GITHUB_STEP_SUMMARY
        echo "4. Access dashboard at the forwarded port 5174" >> $GITHUB_STEP_SUMMARY
